# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Create env file
      run: |
        touch .env
        echo "${{ secrets.SECRET_ENV }}" > .env
    - name: Build docker image
      run: docker build --target test --tag todo_app:test .
    - name: Run tests
      run: docker run todo_app:test
