# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master, Exercise-9 ]
  pull_request:
    branches: [ master ]

jobs:
  build_and_test:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Create env file
      run: |
        touch .env
        echo "${{ secrets.SECRET_ENV }}" > .env
    - name: Build docker image for unit and integration tests
      run: docker build --target test_unit_integration --tag todo_app:test_unit_integration .
    - name: Run unit and integration tests
      run: docker run todo_app:test_unit_integration
    - name: Build docker image for e2e tests
      run: docker build --target test_e2e --tag todo_app:test_e2e .
    - name: Run e2e tests
      run: docker run --env-file .env todo_app:test_e2e

  deploy:
    name: Deploy application
    runs-on: ubuntu-latest
    needs: [build_and_test]
    if: ${{ (github.event_name == 'push') && (github.ref == 'refs/heads/Exercise-9') }}
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
      HEROKU_API_KEY:  ${{ secrets.HEROKU_API_KEY }}
      AZURE_DEPLOY_WEBHOOK: ${{ secrets.AZURE_DEPLOY_WEBHOOK }}
    steps:
    - uses: actions/checkout@v2
    - name: Login to Docker
      run: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
    - name: Build and push to Docker Hub
      run: |
        docker build --target production --tag $DOCKER_USERNAME/todo_app:latest .
        docker push $DOCKER_USERNAME/todo_app:latest
    - name: Release app on Azure
      run: curl -dh -X POST $AZURE_DEPLOY_WEBHOOK

