# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master, Exercie-8 ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Create env file
      run: |
        touch .env
        echo "${{ secrets.SECRET_ENV }}" > .env
    - name: Build docker image for unit and integration tests
      run: docker build --target test_unit_integration --tag todo_app:test_unit_integration .
    - name: Run unit and integration tests
      run: docker run todo_app:test_unit_integration
    - name: Build docker image for e2e tests
      run: docker build --target test_e2e --tag todo_app:test_e2e .
    - name: Run e2e tests
      run: docker run --env-file .env todo_app:test_e2e

  deploy:
    name: Deploy application
    runs-on: ubuntu-latest
    needs: [build-and-test]
    if: ${{ (github.event_name == 'push') && (github.ref == 'refs/heads/Exercise-8') }}
    steps:
    - uses: actions/checkout@v2
    - name: Login to Docker
  
      run: docker login --username ${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and push to Docker Hub
      run: |
        docker build --target production --tag ${{ secrets.DOCKER_USERNAME }}/todo_app:latest .
        docker push ${{ secrets.DOCKER_USERNAME }}/todo_app:latest
    - name: Rename tag to Heroku app name
    - name: Login to docker registry
      run: docker tag ${{ secrets.DOCKER_USERNAME }}/todo_app registry.heroku.com/${{ secrets.HEROKU_APP_NAME }}/web
      run: docker login --username ${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.HEROKU_API_KEY }} registry.heroku.com
    - name: Push to heroku registry
      run: docker push registry.heroku.com/${{ secrets.HEROKU_APP_NAME }}/web
    - name: Release app
      run: HEROKU_API_KEY=${{ secrets.HEROKU_API_KEY }} heroku container:release web -a ${{ secrets.HEROKU_APP_NAME }}

